id: I2D57AA51
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T19:57:51.663340'
last_modified: '2022-06-18T19:57:51.663356'
parser: null
source_metadata:
  title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
  author: tsong kha pa blo bzang grags pa/
  description: 'Digital version 1.0 {Wylie}, diplomatic edition of witness A; WYLIE
    COPY of master xml (completed: 2020-08-19); revised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:klu grub/ (Gongkar Choede) (ld)
  - Editorial process:-
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4868
  bases:
    b585:
      title: Exposition of the Cakrasaṃvaratantra (block print), colophon excerpt
      order: 1
      base_file: b585.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
